---
name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  create-issue-on-failure:
    name: Create Issue on Failure
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Create Issue on Failure
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_LINK: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          filename: .github/nightly-build-failure-issue-template.md
          update_existing: true
