---
name: Build Firmware

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.appliance.name }} Firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appliance:
          - name: electric_tank_water_heater
            shorthand: etwh
          - name: heatpump_water_heater
            shorthand: hpwh
          - name: hvac
            shorthand: hvac
          - name: tankless_water_heater
            shorthand: tlwh
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.x"
      - name: Build firmware
        uses: esphome/build-action@v1.8.0
        id: esphome-build
        with:
          yaml_file: econet_${{ matrix.appliance.name }}.yaml
          version: latest
