---
name: Build Firmware

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install ESPHome
        run: pip install --user esphome
      - name: ESPHome Build Cache
        uses: actions/cache@v3
        with:
          path: ./.esphome
          key: ${{ github.workflow }}-${{ runner.os }}-.esphome
      - name: Compile Release Firmware
        run: |
          esphome compile \
          econet_heatpump_water_heater.yaml  \
          econet_hvac.yaml \
          econet_tankless_water_heater.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
