---
name: Build Firmware

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Firmware

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Install ESPHome
        run: pip install --user esphome

      - name: Compile Release Firmware
        run: |
          esphome compile \
          econet_heatpump_water_heater.yaml  \
          econet_hvac.yaml \
          econet_tankless_water_heater.yaml
