---
name: Build Firmware

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install ESPHome
        run: pip install --upgrade esphome
      - name: Create Stub Secrets File
        run: |
          echo 'wifi_ssid: "STUB_SSID"' >> secrets.yaml
          echo 'wifi_password: "STUB_PASSWORD"' >> secrets.yaml
      - name: Verify All Configurations
        run: |
          esphome -s external_components_source components config \
          econet_electric_tank_water_heater.yaml \
          econet_heatpump_water_heater.yaml  \
          econet_hvac.yaml \
          econet_tankless_water_heater.yaml \
          example-local.yaml
      - name: Compile Firmware
        run: |
          esphome -s external_components_source components compile \
          econet_electric_tank_water_heater.yaml \
          econet_heatpump_water_heater.yaml  \
          econet_hvac.yaml \
          econet_tankless_water_heater.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
